#! /bin/sh

bspc config border_width        3
bspc config window_gap         18

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

# Monitors
bspc monitor DVI-I-1 -n 体 -d 一 二 三 四 五
bspc monitor DVI-D-0 -n 左腕 -d 六 七 八 九 十

#bspc rule -a Gimp desktop=^8 follow=on
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a keepassx desktop=^9

# Initialize panel
panel &
